env:
  browser: yes
extends: 'eslint:recommended'
rules:
  comma-spacing:
    - error
  linebreak-style:
    - error
    - unix
  no-shadow:
    - error
  no-unused-vars:
    - error
  semi:
    - error
    - always

